# Generated by Django 3.0.8 on 2020-09-19 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
