# Generated by Django 3.0.8 on 2020-09-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
